export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const ALL_AUCTIONS_REQUEST = "ALL_AUCTIONS_REQUEST";
export const ALL_AUCTIONS_SUCCESS = "ALL_AUCTIONS_SUCCESS";
export const ALL_AUCTIONS_FAIL = "ALL_AUCTIONS_FAIL";

export const AUCTION_DETAILS_REQUEST = "AUCTION_DETAILS_REQUEST";
export const AUCTION_DETAILS_SUCCESS = "AUCTION_DETAILS_SUCCESS";
export const AUCTION_DETAILS_FAIL = "AUCTION_DETAILS_FAIL";

export const NEW_AUCTION_REQUEST = "NEW_AUCTION_REQUEST";
export const NEW_AUCTION_SUCCESS = "NEW_AUCTION_SUCCESS";
export const NEW_AUCTION_FAIL = "NEW_AUCTION_FAIL";

export const NEW_BID_REQUEST = "NEW_BID_REQUEST";
export const NEW_BID_SUCCESS = "NEW_BID_SUCCESS";
export const NEW_BID_RESET = "NEW_BID_RESET";

export const ALL_BIDS_REQUEST = "ALL_BIDS_REQUEST";
export const ALL_BIDS_SUCCESS = "ALL_BIDS_SUCCESS";
export const ALL_BIDS_FAIL = "ALL_BIDS_FAIL";

export const AUCTION_END_REQUEST = "AUCTION_END_REQUEST";
export const AUCTION_END_SUCCESS = "AUCTION_END_SUCCESS";
export const AUCTION_END_FAIL = "AUCTION_END_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
